apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "hiedu-backend-config"}'
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2025-05-24T15:25:46Z"
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  name: hiedu-k8s-service
  labels:
    argocd.argoproj.io/instance: hiedu-argo
    app: hiedu-k8s-deployment
    app.kubernetes.io/managed-by: cloud-console
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: hiedu-k8s-deployment
    app.kubernetes.io/managed-by: cloud-console
  sessionAffinity: None
  type: LoadBalancer
