apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "hiedu-backend-config"}'
    ingress.gcp.kubernetes.io/pre-shared-cert: mcrt-506d2643-c6d0-4cdb-85c0-f4af9d397a47
    ingress.kubernetes.io/backends: '{"k8s1-a3481635-default-hiedu-k8s-deployment-z9s9r-80-a8101ed0":"HEALTHY"}'
    ingress.kubernetes.io/https-forwarding-rule: k8s2-fs-7xdr9v6b-default-hiedu-ingress-4bq85xqh
    ingress.kubernetes.io/https-target-proxy: k8s2-ts-7xdr9v6b-default-hiedu-ingress-4bq85xqh
    ingress.kubernetes.io/ssl-cert: mcrt-506d2643-c6d0-4cdb-85c0-f4af9d397a47
    ingress.kubernetes.io/url-map: k8s2-um-7xdr9v6b-default-hiedu-ingress-4bq85xqh
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: hiedu-certificate
  labels:
    argocd.argoproj.io/instance: hiedu-argo
  creationTimestamp: "2025-05-24T16:05:42Z"
  finalizers:
    - networking.gke.io/ingress-finalizer-V2
  generation: 3
  name: hiedu-ingress
  namespace: default
  resourceVersion: "1748107000303279009"
  uid: 189b909e-11f4-4780-bcc9-cd7f832be8d0
spec:
  defaultBackend:
    service:
      name: hiedu-k8s-deployment-z9s9r
      port:
        number: 80
  rules:
    - host: hiedu.site
      http:
        paths:
          - backend:
              service:
                name: hiedu-k8s-deployment-z9s9r
                port:
                  number: 80
            path: /
            pathType: Prefix
status:
  loadBalancer:
    ingress:
      - ip: 34.117.107.180
